name: Go Tests

on:
  push:
    branches:
      - master


jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/setup-go@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.20

      - name: Run Tests
        run: go test ./Test/